//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Craig.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Call()
        {
            this.Resolutions = new HashSet<Resolution>();
        }
    
        public int Id { get; set; }
        public int Platform_Id { get; set; }
        public int Location_Id { get; set; }
        public string Severity { get; set; }
        public int User_Id { get; set; }
        public string Extension { get; set; }
        public string Details { get; set; }
        public System.DateTime TimeOpened { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string State { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resolution> Resolutions { get; set; }
    }
}
