//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Craig.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CraigDBEntities : DbContext
    {
        public CraigDBEntities()
            : base("name=CraigDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Call> Calls { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Platform> Platforms { get; set; }
        public virtual DbSet<Resolution> Resolutions { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
